### ISSUE TITLE
rest.pull_item with vault=True not working as expected

### ISSUE THREAD

**Issue by NoahDReifsnyder** [nxtlo/aiobungie#418]
### Long story short.

When supplying vault=True to rest.pull_item, the item is pulled to character inventory instead. 

### Expected Result

The item should have been pulled directly to vault, or at least pulled to character and then to vault
### Actual Result

item was pulled to inventory and left there
### Platform + aiobungie(version) Info

Running on Windows 11, python 3.12, with aiobungie version 0.2.11
### Further info

From my inspection of the Destiny2 API, I'm not sure if moving directly from postmaster to Vault is even possible. If it is not possible, aiobungie documentation should reflect that. The documentation currently says you can supply vault=True to pull_item to have the item go to vault

**Comment by nxtlo** [comment]
Looking at the official documentations for this route, they changed the JSON payload field name from `vault` to `transferToValut`, should be pretty easy to fix.

unfortunately there're no decent documentation or changelog for the API so we kinda have to just catch stuff ourselves :)
anyways thatnks for catching that.

for the postmaster part im pretty sure its possible but it'll require two requests, the first is to pull the item, the second is transfring the item with `valut` option. so you basically pull the item to the character then transfer it to the valut.

**Comment by NoahDReifsnyder** [comment]
I'm currently using two requests as you described, but I would like a way to not disturb character inventory if possible. (also it's nice to keep requests as low as possible)

**Comment by NoahDReifsnyder** [comment]
I get around not disturbing inventory (if its full already) by moving an item from character to vault, pulling from postmaster to character, moving postmater item from character to vault, and then returning the original item from vault to character. If these 4 requests could be condensed to one (a direct move from postmaster to the vault) that would be a great improvement.

**Comment by nxtlo** [comment]
ok this issue has been resolved and pushed to master, i kept the `vault` option since i've seen that its useful.

it basically perform an extra HTTP request to do what you described, *only if this option set to `True`*
but you should read the documentation about this option again as well and what it actually does.

you may close issue this whenever your issue is resolved.

**Comment by nxtlo** [comment]
> (a direct move from postmaster to the vault)

that would be pretty usefull i agree, but i don't think there's any other way besides what you just described.

**Comment by NoahDReifsnyder** [comment]
Appreciate you looking into it! ill close now, and continue using the multi step process going forward
